# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shahmeer Navid
description: > # this means to ignore newlines until "baseurl:"
  Shahmeer Navid - Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shahmeer.co" # the base hostname & protocol for your site, e.g. http://example.com
email: "shahmeernavid@gmail.com"
linkedin_url: "https://ca.linkedin.com/pub/shahmeer-navid/41/a16/6b4"
github_username:  shamwow
excerpt_separator: <!-- read more -->
logo_height: 119
logo_width: 57
permalink: /:title.html


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - save
